services:
  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ~/.pg/pg_data/DT_TT:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${EXTERNAL_DB_PORT}:${INTERNAL_DB_PORT}"
    networks:
      - custom

  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - database
    command: >
      sh -c "sleep 10 && alembic upgrade head && python3 -m src.main"
    networks:
      - custom

networks:
  custom:
    driver: bridge
